# Generated by Django 4.2.25 on 2025-11-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labeledimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='labeledimage',
            name='dataset_split',
            field=models.CharField(choices=[('train', 'Training Set'), ('test', 'Test Set'), ('val', 'Validation Set')], default='train', max_length=10),
        ),
        migrations.AddField(
            model_name='labeledimage',
            name='needs_correction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labeledimage',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labeledimage',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labeledimage',
            name='verified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
